PUT http://localhost:8000/api/gallery/6516e116e24272b5ebb76c2a
Content-Type: application/json

{
    "text": "xoxo",

}

###

GET http://localhost:8000/api/gallery

###

POST http://localhost:8000/api/gallery/new
Content-Type: application/json

{
    "image": "https://unsplash.com/photos/a-train-traveling-through-a-valley-covered-in-snow-CO5BhPPhkkY",
    "dimensions": "5ft x 3ft",
    "medium": "Acrylic on canvas",
    "title": "Raiia is the best <3<3<3",
    "text": "I love her so much she cooked me food i love you babyyyyyyy",
    "width": 10,
    "height": 17 
}

###

DELETE http://localhost:8000/api/gallery/delete/651a996780279e5bd6d17d47


###
